import Link from "next/link";

const lessonData: Record<string, { number: string; level: string; title: string; intro: string; topics: string[]; code: string }> = {
  "python-fundamentals": { number: "01", level: "Volume I · Foundation", title: "Python fundamentals", intro: "Begin with the ideas that make Python feel less like a collection of rules and more like a language you can reason about.", topics: ["What Python is and how it runs", "Installing Python and choosing a version", "The interpreter, scripts, and virtual environments", "Your first deliberate program"], code: 'name = "Ada"\nprint(f"Welcome, {name}.")' },
  "data-structures": { number: "02", level: "Volume I · Foundation", title: "Data structures", intro: "Choose the right shape for your data, then learn the small set of operations that turn collections into useful programs.", topics: ["Lists, tuples, dictionaries, and sets", "Mutability and references", "Iteration and collection helpers", "Writing readable transformations"], code: 'reading = {"title": "Python", "minutes": 42}\nprint(reading["title"])' },
  "functions-and-scope": { number: "03", level: "Volume I · Foundation", title: "Functions & scope", intro: "Give your ideas names. Functions make programs easier to test, explain, and change without fear.", topics: ["Defining functions and returning values", "Parameters, arguments, and defaults", "LEGB scope and closures", "Docstrings and annotations"], code: 'def greet(name: str) -> str:\n    return f"Hello, {name}."' },
  "object-oriented-python": { number: "04", level: "Volume II · Craft", title: "Object-oriented Python", intro: "Model the things your software cares about with classes that have clear responsibilities and honest boundaries.", topics: ["Classes, objects, and constructors", "Encapsulation and properties", "Inheritance and polymorphism", "Dataclasses and dunder methods"], code: '@dataclass\nclass Book:\n    title: str\n    author: str' },
  "testing-and-quality": { number: "05", level: "Volume II · Craft", title: "Testing & quality", intro: "Confidence is a feature. Build a test suite that protects behavior and lets you improve your design safely.", topics: ["Unit tests with unittest", "Pytest fixtures and parametrization", "Mocks and external boundaries", "Coverage as a conversation"], code: 'def test_total():\n    assert total([10, 5]) == 15' },
  "async-concurrency": { number: "06", level: "Volume III · Mastery", title: "Async & concurrency", intro: "Learn how Python handles waiting, work, and pressure so your systems can stay responsive as they grow.", topics: ["Threads, processes, and the GIL", "Event loops and coroutines", "Tasks, queues, and cancellation", "Choosing the right concurrency model"], code: 'async def fetch_profile(client, user_id):\n    return await client.get(f"/users/{user_id}")' }
};

export default async function LessonPage({ params }: { params: { slug: string } }) {
  const lesson = lessonData[params.slug] ?? lessonData["python-fundamentals"];
  return <main className="min-h-screen paper-grain"><nav className="mx-auto flex max-w-[1100px] items-center justify-between px-6 py-6 lg:px-10"><Link href="/" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full border border-brass text-sm font-bold text-brass">Py</span><span className="serif text-xl font-semibold">The Python Atelier</span></Link><Link href="/#library" className="text-xs font-bold uppercase tracking-[.14em] text-ink/60 hover:text-brass">← Reading room</Link></nav><article className="mx-auto max-w-[900px] px-6 pb-24 pt-16 lg:px-10 lg:pt-24"><p className="eyebrow text-brass">{lesson.level} · Lesson {lesson.number}</p><h1 className="serif mt-7 max-w-3xl text-6xl leading-[.9] tracking-tight sm:text-8xl">{lesson.title}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-ink/60">{lesson.intro}</p><div className="my-14 rule" /><div className="grid gap-12 lg:grid-cols-[1fr_1.15fr]"><div><p className="eyebrow mb-5 text-brass">In this lesson</p><ul className="space-y-5">{lesson.topics.map((topic) => <li key={topic} className="flex gap-4 text-sm leading-6"><span className="text-brass">✦</span><span>{topic}</span></li>)}</ul></div><div className="rounded-sm bg-forest p-6 text-cream shadow-xl"><div className="mb-6 flex items-center justify-between border-b border-cream/15 pb-4"><span className="eyebrow text-brass">A first taste</span><span className="text-xs text-cream/40">python</span></div><pre className="overflow-x-auto text-sm leading-7 text-[#e5d9bb]"><code>{lesson.code}</code></pre><p className="mt-8 border-t border-cream/15 pt-4 text-xs leading-5 text-cream/45">Read the full Markdown curriculum in the repository for the complete lesson.</p></div></div><div className="mt-16 flex flex-wrap gap-4"><Link href="/" className="rounded-sm bg-forest px-6 py-4 text-xs font-bold uppercase tracking-[.14em] text-cream hover:bg-ink">Back to the collection</Link><a href="https://github.com/HesamPourAbbasian/python-journey" target="_blank" rel="noreferrer" className="border border-line px-6 py-4 text-xs font-bold uppercase tracking-[.14em] text-forest hover:border-brass">Open full curriculum ↗</a></div></article></main>;
}
