"use client";

import { useState } from "react";

type Course = { level: string; title: string; copy: string; count: string; tone: string; icon: string };

const courses: Course[] = [
  { level: "I · Foundation", title: "The First Principles", copy: "Learn to think in Python. Syntax, data, flow, and the habits that make every future line feel inevitable.", count: "48 lessons", tone: "bg-[#e9dfc9]", icon: "01" },
  { level: "II · Craft", title: "The Working Engineer", copy: "Turn scripts into software with object design, testing, typing, databases, APIs, and elegant abstractions.", count: "43 lessons", tone: "bg-[#d5dfd1]", icon: "02" },
  { level: "III · Mastery", title: "The Systems Mind", copy: "Meet the runtime. Concurrency, security, architecture, deployment, data, and the questions senior engineers ask.", count: "39 lessons", tone: "bg-[#c9d4d2]", icon: "03" }
];

const modules = ["Python fundamentals", "Data structures", "Functions & scope", "Object-oriented Python", "Testing & quality", "Async & concurrency"];

export default function Home() {
  const [query, setQuery] = useState("");
  const [menuOpen, setMenuOpen] = useState(false);
  const filtered = modules.filter((item) => item.toLowerCase().includes(query.toLowerCase()));

  return <main className="min-h-screen paper-grain">
    <nav className="mx-auto flex max-w-[1320px] items-center justify-between px-6 py-6 lg:px-10">
      <a href="#top" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full border border-brass text-sm font-bold text-brass">Py</span><span className="serif text-xl font-semibold tracking-tight">The Python Atelier</span></a>
      <div className="hidden items-center gap-9 text-xs font-bold uppercase tracking-[.14em] text-ink/65 md:flex"><a href="#curriculum" className="transition hover:text-brass">Curriculum</a><a href="#method" className="transition hover:text-brass">Our method</a><a href="#library" className="transition hover:text-brass">Library</a><button className="border-b border-brass pb-1 text-ink">Sign in <span className="ml-2 text-brass">↗</span></button></div>
      <button aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)} className="text-2xl md:hidden">{menuOpen ? "×" : "☰"}</button>
    </nav>
    {menuOpen && <div className="mx-6 mb-5 space-y-3 border-y border-line py-4 text-sm font-bold md:hidden"><a className="block" href="#curriculum">Curriculum</a><a className="block" href="#method">Our method</a><a className="block" href="#library">Library</a></div>}

    <section id="top" className="mx-auto grid max-w-[1320px] gap-12 px-6 pb-24 pt-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-10 lg:pt-20">
      <div><p className="eyebrow mb-7 text-brass">A considered education in Python</p><h1 className="serif max-w-3xl text-6xl leading-[.91] tracking-[-.04em] text-ink sm:text-8xl">Learn the language.<br /><em className="font-normal text-forest">Keep the craft.</em></h1><p className="mt-8 max-w-lg text-base leading-8 text-ink/65">A beautifully structured, deeply practical path from your first <code className="rounded bg-[#e8e1d2] px-1.5 py-0.5 text-sm text-forest">print()</code> to production systems. No noise. Just the good stuff.</p><div className="mt-9 flex flex-wrap items-center gap-5"><a href="#curriculum" className="rounded-sm bg-forest px-7 py-4 text-xs font-bold uppercase tracking-[.15em] text-cream shadow-lg shadow-forest/10 transition hover:bg-ink">Explore the curriculum <span className="ml-6 text-brass">→</span></a><span className="text-xs text-ink/45">Self-paced · Always free</span></div></div>
      <div className="relative mx-auto w-full max-w-[540px] lg:ml-auto"><div className="absolute -right-2 -top-5 z-10 flex h-28 w-28 rotate-6 flex-col items-center justify-center rounded-full border border-brass bg-[#f5f1e7] text-center shadow-xl"><span className="serif text-2xl text-brass">Est.</span><span className="eyebrow text-[.5rem]">for curious minds</span></div><div className="olive-glow relative overflow-hidden rounded-sm px-8 pb-8 pt-10 text-cream shadow-2xl shadow-forest/20 sm:px-12"><div className="absolute -right-12 bottom-0 text-[240px] font-black leading-none text-white/[.035]">{`{ }`}</div><div className="relative"><div className="mb-24 flex items-center justify-between"><span className="eyebrow text-brass">Volume one</span><span className="text-xs text-cream/45">01 / 03</span></div><p className="serif text-5xl leading-none sm:text-6xl">The<br /><span className="italic text-[#d6bf91]">quiet</span> power<br />of Python.</p><div className="mt-20 flex items-end justify-between border-t border-cream/15 pt-4"><span className="text-xs text-cream/55">Begin at the beginning</span><span className="serif text-4xl text-brass">⌁</span></div></div></div></div>
    </section>

    <section className="border-y border-line bg-[#f0eadc]/70"><div className="mx-auto grid max-w-[1320px] grid-cols-2 divide-x divide-line px-6 lg:grid-cols-4 lg:px-10"><Stat value="130+" label="carefully written lessons" /><Stat value="24" label="hands-on projects" /><Stat value="3" label="levels of progression" /><Stat value="∞" label="room to grow" /></div></section>

    <section id="curriculum" className="mx-auto max-w-[1320px] px-6 py-24 lg:px-10"><div className="mb-12 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow mb-4 text-brass">The collection</p><h2 className="serif text-5xl tracking-tight sm:text-6xl">A proper way to learn.</h2></div><p className="max-w-xs text-sm leading-6 text-ink/55">Three volumes. One clear progression. Built for the long view.</p></div><div className="grid gap-5 lg:grid-cols-3">{courses.map((course) => <article key={course.level} className={`${course.tone} group relative min-h-[360px] overflow-hidden rounded-sm p-7 transition hover:-translate-y-1 hover:shadow-xl`}><div className="flex items-start justify-between"><span className="eyebrow text-ink/50">{course.level}</span><span className="serif text-2xl text-ink/35">{course.icon}</span></div><div className="absolute -bottom-10 -right-3 serif text-[180px] leading-none text-ink/[.055]">✦</div><div className="relative mt-24"><h3 className="serif max-w-xs text-4xl leading-none">{course.title}</h3><p className="mt-4 max-w-sm text-sm leading-6 text-ink/60">{course.copy}</p><div className="mt-6 flex items-center gap-3 text-xs font-bold text-forest"><span>{course.count}</span><span className="h-px w-8 bg-brass" /><span>View volume →</span></div></div></article>)}</div></section>

    <section id="method" className="olive-glow text-cream"><div className="mx-auto grid max-w-[1320px] gap-14 px-6 py-24 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><p className="eyebrow mb-5 text-brass">The atelier method</p><h2 className="serif text-5xl leading-[.95] sm:text-6xl">Depth over<br /><i className="text-[#d6bf91]">shortcuts.</i></h2><p className="mt-7 max-w-sm text-sm leading-7 text-cream/60">Most tutorials teach you what to type. We take the time to show you why it works, when it breaks, and how to make it yours.</p></div><div className="grid gap-8 sm:grid-cols-2">{[["01", "Read with purpose", "Every lesson starts with a mental model, then earns its code."], ["02", "Make it real", "Small exercises become useful tools you can keep and improve."], ["03", "Return often", "A good reference is not finished. It grows with your questions."], ["04", "Build judgment", "Learn the trade-offs behind the syntax, not just the syntax itself."]].map(([num, title, copy]) => <div key={num} className="border-t border-cream/20 pt-5"><span className="eyebrow text-brass">{num}</span><h3 className="serif mt-6 text-3xl">{title}</h3><p className="mt-3 text-sm leading-6 text-cream/55">{copy}</p></div>)}</div></div></section>

    <section id="library" className="mx-auto max-w-[1320px] px-6 py-24 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow mb-5 text-brass">The reading room</p><h2 className="serif text-5xl leading-none sm:text-6xl">Find your<br /><i>next lesson.</i></h2><p className="mt-6 text-sm leading-7 text-ink/55">Browse the complete index of thoughtfully sequenced topics.</p><div className="relative mt-8"><span className="absolute left-4 top-3.5 text-ink/35">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search the library" className="w-full rounded-sm border border-line bg-transparent py-3 pl-10 pr-4 text-sm outline-none transition focus:border-brass" /></div></div><div className="divide-y divide-line border-y border-line">{filtered.length ? filtered.map((module, index) => <div key={module} className="group flex items-center justify-between py-5"><div className="flex items-center gap-5"><span className="serif text-xl text-brass">0{index + 1}</span><span className="text-sm font-semibold">{module}</span></div><span className="text-lg text-ink/30 transition group-hover:translate-x-1 group-hover:text-brass">↗</span></div>) : <p className="py-8 text-sm text-ink/55">No lessons found. Try another phrase.</p>}<div className="flex items-center justify-between py-5 text-xs font-bold uppercase tracking-[.14em] text-forest"><span>View all 130+ lessons</span><span className="text-brass">→</span></div></div></div></section>

    <footer className="border-t border-line bg-[#eee7d7]"><div className="mx-auto flex max-w-[1320px] flex-col gap-7 px-6 py-10 sm:flex-row sm:items-center sm:justify-between lg:px-10"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full border border-brass text-xs font-bold text-brass">Py</span><span className="serif text-lg">The Python Atelier</span></div><p className="text-xs text-ink/45">A complete learning journey, made with care.</p><div className="flex gap-5 text-xs font-bold uppercase tracking-widest text-ink/55"><a href="#top">Back to top ↑</a></div></div></footer>
  </main>;
}

function Stat({ value, label }: { value: string; label: string }) { return <div className="px-4 py-7 first:pl-0 last:pr-0 sm:px-7"><p className="serif text-4xl text-forest">{value}</p><p className="mt-1 text-[.65rem] font-bold uppercase leading-4 tracking-widest text-ink/45">{label}</p></div>; }
